### ISSUE TITLE
Applying new outside algorithms on gold166

### ISSUE THREAD

**Issue by kdmarrett** [BigNeuron/Data#4]
Is there a copy of the gold166 where the image stacks are in 2D tiff series like the DIADEM dataset? I ask because the v3draw and v3dpbd.tif files have to be converted 1 by 1 manually in FIJI or vaa3d, which is very time consuming. Also, I'm still not sure how to convert v3draw to 2d tif series, as vaa3d does not allow me to import it without an error.

I'd love to check my method against this high quality data but my application is too large to be included in the vaa3d project so I would have to rewrite file reading of v3draw and v3dpbd formats or manually convert just to compare my method, and these two formats are application (Vaa3d) specific.

Also, why doesn't the latest publication of this BigNeuron dataset compare the algorithms with the DIADEM metric?

By the way, some are these are more discussions than issues, github has an ability to add a discussion tab to a repository. Keeping these here rather than email if future researchers have similar thoughts.

Thank you for your time and for providing such a valuable resource,

**Comment by hanchuan** [comment]
you may easily convert the formats (which is actually pretty simple format)
using vaa3d plugins, or directly call a plugin to load the data

**Comment by kdmarrett** [comment]
ok I'll attempt to convert from the Vaa3D command line, is there documentation for that somewhere? We tried using FIJI's plugin for converting the v3dpbd but some images crash FIJI even on a system with 64 GB RAM

**Comment by lmanubens** [comment]
Dear Karl,

Thank you for your interest!
The usage of the command line for image format conversion should be quite direct:
`v3d -x convert_file_format -f convert_format -i input_image_file.v3dpbd -o output_image_file.tif`

You should also be able to use:
`v3d -x save_z_slizes -f save_z_slices_to_file_series -i input_image_file -p parameters_string -o output_image_file_prefix`

parameters_string: Range (startslice:increment:endslicenum)    (startslice is 1-based, endslicenum can be 'e', increment can be 1,2,...)    (example: 1:1:e)

I just saw this last comment, I apologize for the late reply.

In regards to:

> Also, why doesn't the latest publication of this BigNeuron dataset compare the algorithms with the DIADEM metric?

As we mention in the main text, "To assess reconstruction quality, we plotted the bi-directional average distance between pairs of neurons for each reconstruction method. Other approaches include the DIADEM metric, which quantifies the similarity between two reconstructions of the same neuron by matching the locations of bifurcations and terminations as well as their topology between the two reconstructed arbors[29](https://www.nature.com/articles/s41592-023-01848-5#ref-CR29), or tree distances based on persistence homology[44](https://www.nature.com/articles/s41592-023-01848-5#ref-CR44),[50](https://www.nature.com/articles/s41592-023-01848-5#ref-CR50). Our approach to calculating tree distances is a simple and fast approximation, given that solving this problem is beyond the scope of this study." 

In fact, we think the mentioned tree-edit distances based on persistence homology could also be an equally valid option. That is indeed an interesting open debate. In any case, we look forward to results with other tree edit distances, and specially, to further work comparing the existing alternatives in depth.

**Comment by kdmarrett** [comment]
Awesome, thank you!

**Comment by kdmarrett** [comment]
Is there a way to run the plugins from the microsoft installation? When I run ./vaa3d_msvc.exe -x plugin_name ... it says key -x your input is illegal
